name: Drew Gottlieb
description: Software Developer
meta_description: "My projects, experiments, successes, and failures."
baseurl: ''

include: ['.htaccess']

markdown: redcarpet
redcarpet:
  extensions:
    - lax_spacing
highlighter: pygments
logo: 'http://www.gravatar.com/avatar/bdf8f49aa6db2d48e5a5ead52af9009e?s=600'
paginate: 4

author:         
  name: 'Drew Gottlieb'
  website: 'http://minipenguin.com'
  bio: I'm a software developer studying at the Rochester Institute of Technology.
    I'm passionate about combining software, hardware, and media to build things people love.
  image: 'http://www.gravatar.com/avatar/bdf8f49aa6db2d48e5a5ead52af9009e?s=600'

# Details for the RSS feed generator
url:            'http://minipenguin.com'
