name: Drew Gottlieb
description: I make things with code and wires
meta_description: "My projects, experiments, successes, and failures."

markdown: redcarpet
highlighter: pygments
logo: false
profileimage: 'http://www.gravatar.com/avatar/bdf8f49aa6db2d48e5a5ead52af9009e?s=600'
paginate: 10

# Details for the RSS feed generator
url: 'www.blog.minipenguin.com'
author: 'Drew Gottlieb'
author_description: I'm a software developer studying at the Rochester Institute of Technology.
  I'm passionate about combining software, hardware, and other media to build things people love.

navlinks:
  - title: About
    url: /about.html
  - title: Projects
    url: https://github.com/dag10
